// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://navlxvufcajsozhvbulu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hdmx4dnVmY2Fqc296aHZidWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3ODMxMTksImV4cCI6MjA3NjM1OTExOX0.VU-Gumfe6BoZHS9cOg8D9dMNg_8HCoiOKJb7bYwDZd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});